title:  BI Conference Deadlines
author: Gi-Cheon Kang
description: Conference Deadlines for Biointelligence Lab.

domain: "biconf.github.io"
baseurl: ""

github_username: biconf
github_repo: biconf.github.io

markdown: kramdown
ga_id: UA-36274081-2
